version: 2

project_name: s3lo

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/s3lo
    binary: s3lo
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: OuFinx
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/OuFinx/s3lo"
    description: "Use AWS S3 as a container image registry"
    license: "MIT"
    test: |
      system "#{bin}/s3lo", "version"

release:
  github:
    owner: OuFinx
    name: s3lo
